env: "cyborg"

env_args:
  key: cyborg
  map_name: cyborg
  wrapper_type: raw
  no_obs: False
  action_masking: False
  episode_trace: False
  time_limit: 30
  pretrained_wrapper: null

test_greedy: True
test_nepisode: 30
test_interval: 10000
log_interval: 50000
runner_log_interval: 10000
learner_log_interval: 10000
t_max: 2050000
save_model: True
save_model_interval: 500000
